version: "3.9"
services:
  app:
    image: app
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: example
      POSTGRES_HOST: db
    ports: 
      - 3000:3000
    networks:
    - my_network
  db:
    image: postgres:alpine3.18
    ports: 
      - "5432:5432"
    networks:
    - my_network
    environment:
      POSTGRES_PASSWORD: example
networks:
  my_network: